drop table if exists employees CASCADE ;
create table employees (id integer generated by default as identity, email varchar(255) not null, full_name varchar(255) not null, primary key (id));
insert into employees (id, email, full_name) values (1, 'Goutam Sikder', 't1@gm.com');